# Generated by Django 3.1.2 on 2020-10-21 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floppy', '0003_note_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='created_at',
            new_name='date_created',
        ),
    ]
