# Generated by Django 3.1.2 on 2020-10-21 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floppy', '0004_auto_20201021_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
