# Generated by Django 3.1.2 on 2020-11-05 15:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floppy', '0010_auto_20201105_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='notelog',
            name='change_content',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notelog',
            name='change_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notelog',
            name='action_flag',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Change'), (2, 'Deletion')], verbose_name='action flag'),
        ),
    ]
