# Generated by Django 3.1.2 on 2020-11-11 20:05

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('floppy', '0013_note_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteCareTaker',
            fields=[
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='floppy.note')),
            ],
        ),
        migrations.CreateModel(
            name='NoteMemento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('care_taker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floppy.notecaretaker')),
            ],
        ),
    ]
