# Generated by Django 3.1.2 on 2020-11-17 21:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('floppy', '0015_delete_notelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_modified',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
